# In-Class Programming Activity, Day 8

### *Hannah Sonsalla*

## Task 1
```{r}
x = runif(100, 20, 70)
y = 5 + 3*x + 2*rnorm(100)
My_data = data.frame(x,y)
plot(My_data)
```
```{r}
LL_line = function(params){
  m = params[1]
  b = params[2]
  sigma = params[3]
  sum(log(dnorm(y - (m * x + b), sd = sigma)))
}

testA = LL_line(c(3,5,2))
testB = LL_line(c(4,1,10))

starting_params <- c(4, 1, 10)
best_optim <- optim(starting_params, LL_line, control=list(fnscale = -1))
best_optim

```

## Task 2
```{r}
load(url("http://tiny.cc/dcf/Taxi_trips.rda"))

taxi_likelihood = function(arguments, data=Taxi_trips){
  base_fare = arguments[1]
  per_mile = arguments[2]
  rate = 1/arguments[3]
  excess <- with(data, fare_amount - (base_fare + per_mile*trip_distance))
  sum(log(dexp(excess, rate)+1e-5))
}

start_params = (c(base_fare = 2.00, per_mile = 4.00, params = 1/3))
best = optim(c(2.3, 2, 5), taxi_likelihood, control=list(fnscale=-1), data=Taxi_trips)

plot(fare_amount~trip_distance, data = Taxi_trips, pch = 20)
abline(best$par[1], best$par[2], col = "red", lwd = 3)


```


## Test statements

```{r}
scoreActivity::score253(8)
```