# In-Class Programming Activity, Day 14

### Hannah Sonsalla

### Load data
```{r}
library(glmnet)
GenCont <- read.csv("http://tiny.cc/dcf/GenCont.csv")
```

## Task 1
```{r}
compare_ols_ridge <- function(responses, predictors, lambda=1){
  inds = sample(1:nrow(GenCont), size = nrow(GenCont)/2 )
  Train = predictors[inds,]
  Test = predictors[-inds,]
  
  lm.fit = lm(responses[inds] ~ as.matrix(Train))

  ridgeRegression <- glmnet(as.matrix(Train), responses[inds], alpha = 0)
  
  preds_in = predict(lm.fit, newdata = Train)
  preds_out = predict(lm.fit, newdata = Test)

  preds_glm_in = predict.glmnet(ridgeRegression, newx = as.matrix(Train))
  preds_glm_out = predict.glmnet(ridgeRegression, newx = as.matrix(Test))
  
  ols_in = mean((preds_in - responses[inds])^2)
  ols_out = mean((preds_out - responses[-inds])^2)
  
  ridge_in = mean((preds_glm_in - responses[inds])^2)
  ridge_out = mean((preds_glm_out - responses[-inds])^2)
  
  list(lambda = lambda, ols_in = ols_in, ols_out = ols_out, ridge_in = ridge_in, ridge_out = ridge_out)

}


Shrink_results = compare_ols_ridge(GenCont$Phenotypes, GenCont[,-1])
Shrink_results
```





## Test statements

```{r}
scoreActivity::score253(14)
```