# In-Class Programming Activity, Day 16

### Hannah Sonsalla

## Task 1 - The Knots
```{r}
my_knots = function(x,k){
  qs = (1:k)/(1+k)
  #qs = seq(1/(k+1), 0.9999, by = 1/(k+1))
  quantile(rnorm(1000), probs=qs)
}

my_knots(rnorm(1000), 2)

```

## Task 2 - The Basis Set
```{r}
spline_model_matrix = function(x, knot_locations){
  MM <- cbind(1, x, x^2, x^3)
  for (knot in knot_locations){
    new_vector = (x-knot_locations[knot])^3
    MM <- cbind(MM, new_vector)
  }
  return (MM)
}
```

## Task 3: Best linear combination
```{r}

fit_spline <- function(formula, k=2, data=parent.frame()) {
  y <- eval(formula[[2]], envir=data)
  x <- eval(formula[[3]], envir=data)
  knot_locations <- my_knots(x, k)
  MM <- spline_model_matrix(x, knot_locations)
  mod <- lm(y ~ MM - 1)
  res <- list(coef = coef(mod), knots = knot_locations, cov = vcov(mod))
  class(res) <- "my_spline"
  
  return(res)
}
```


## Task 4: Predict Function
```{r}
predict.my_spline <- 
  function(mod, newx, level = 0.95,
           intervals=c("none", "confidence", "prediction")) {
  intervals <- match.arg(intervals)
  MM <- spline_model_matrix(newx, mod$knots)
  vals <- MM %*% mod$coef
  se <- sqrt(rowSums(MM %*% mod$cov * MM))
  if (intervals == "none") return(vals)
  else return(NULL) # for future use
}
```


## Test statements
Note: These are the wrong tests for this activity.
```{r}
scoreActivity::score253(16)
```